//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PixelShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DONHANG()
        {
            this.CHITIETDONHANGs = new HashSet<CHITIETDONHANG>();
        }
    
        public string MaDH { get; set; }
        public Nullable<System.DateTime> NgayDate { get; set; }
        public Nullable<System.DateTime> NgayGiao { get; set; }
        public Nullable<int> TinhTrang { get; set; }
        public string EmailDat { get; set; }
        public string DiaChiGiao { get; set; }
        public string TenNguoiNhan { get; set; }
        public string SDTNhan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDONHANG> CHITIETDONHANGs { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
        public virtual TINHTRANGDONHANG TINHTRANGDONHANG { get; set; }
    }
}
